apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvuhre4mw-nodejs
  janus-idp.io/tekton: zvuhre4mw-nodejs
  backstage.io/kubernetes-id: zvuhre4mw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvuhre4mw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
